Updated file

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -1,28 +1,29 @@
 #!/usr/bin/env bash
-# Create a script to install and configure HAProxy on lb-01 server
-# Configure HAProxy to send traffic to web-01 and web-02 servers
-# Distribute requests using a roundrobin algorithm
-# Make sure that HAProxy can be managed via an init script
-# Install and configure HAproxy on my lb-01 server.
+# Install HAproxy and configure it to balances two web servers
+
+set -x # Enable xtrace
+set -eo pipefail # Causes the script to exit on error
+
 sudo apt-get -y update
-apt-get -y install haproxy
+sudo apt-get -y install --no-install-recommends software-properties-common
+sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
+sudo apt-get -y install haproxy=2.6.\*
 
-# edit config file
-server_config=\
-"
-frontend  ehoneah-frontend
-        bind *:80
-        mode http
-        default_backend ehoneah-backend
-backend ehoneah-backend
-        balance roundrobin
-        server 63210-web-01 100.25.19.204:80 check
-        server 63210-web-02 54.157.159.85:80 check
-"
-echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
+cat << EOF |sudo tee -a /etc/haproxy/haproxy.cfg
+frontend main
+    bind *:80
+    mode http
+    timeout client 20s
+    default_backend  web
 
-# enable haproxy to be started by init script
-
-echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
-
+backend web
+    mode http
+    timeout connect 20s
+    timeout server 20s
+    balance   roundrobin
+    server 18627-web-01 100.26.212.211:80 check
+    server 18627-web-02 34.202.234.174:80 check
+EOF
+sudo service haproxy start
+sudo service haproxy enable
 sudo service haproxy restart
